urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cs.views.home', name='home'),
    # url(r'^cs/', include('cs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
		(r'^$','cs.views.home'),	
		(r'^videos/',include('videos.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

videos/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('videos.views',
		url(r'^$','index'),
		url(r'^(?P<video_id>\d+)/$','detail'),
		url(r'^streams/(?P<stream_id>\d+)/$','stream_detail'),
)

videos/models.py
from django.db import models

class Tag(models.Model):
	tag_title=models.CharField(max_length=200)

	def __unicode__(self):
		return self.tag_title

class Type(models.Model):
	type_title=models.CharField(max_length=200)

	def __unicode__(self):
		return self.type_title

class Stream(models.Model):
	stream_title=models.CharField(max_length=200)
	stream_description=models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.stream_title
	
	def module_count(self):
		return len(self.association_set.all())
	
	def module_titles(self):
		module_titles=[]
		for association in self.association_set.all():
			module=association.association_module_id.module_title
			module_titles.append(module)
		return '<br /> '.join(module_titles)
	module_titles.allow_tags=True

class Module(models.Model):
	module_associations=models.ManyToManyField(Stream, through='Association')
	module_prereqs=models.ManyToManyField("self", symmetrical=False)

	module_title=models.CharField(max_length=200)
	module_description=models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.module_title

	def stream_titles(self):
		stream_titles=[]
		for association in self.association_set.all():
			stream=association.association_stream_id.stream_title
			stream_titles.append(stream)
		return ', '.join(stream_titles)

class Association(models.Model):
	association_stream_id=models.ForeignKey(Stream)
	association_module_id=models.ForeignKey(Module)
	association_part=models.IntegerField()

	def __unicode__(self):
		return "%s: %s (%d)" % (self.association_stream_id.stream_title, self.association_module_id.module_title, self.association_part)

class Video(models.Model):
	module_id=models.ForeignKey(Module)
	video_type=models.ForeignKey(Type, null=True, blank=True)
	video_tag=models.ManyToManyField(Tag, blank=True, null=True)

	video_url=models.CharField(max_length=200)
	video_title=models.CharField(max_length=200, blank=True)
	video_part=models.IntegerField()

	def __unicode__(self):
		return "%s" % self.module_id.module_title + " ("+str(self.video_part)+")"

	def module_title_part(self):
		return "%s" % self.module_id.module_title + " ("+str(self.video_part)+")"

	def video_youtube_id(self):
		import re
		match=re.search("v=(.*)$",self.video_url)
		if match:
			return match.group(1)
		else:
			return ''

	def video_tags(self):
		tags=[]
		for tag in self.video_tag.all():
			tags.append(tag.tag_title)
		return ', '.join(tags)

videos/views.py
from django.shortcuts import render_to_response
from videos.models import Stream, Video
from django.http import Http404

#send info about request object to template so it can use csrf token
from django.template import RequestContext

def index(request):
	streams_list=Stream.objects.all()
	return render_to_response('videos/index.html',locals())

def stream_detail(request,stream_id):
	try:
		stream=Stream.objects.get(pk=stream_id)
		associations_list=stream.association_set.all()
	except Stream.DoesNotExist:
		raise Http404
	return render_to_response('videos/stream_detail.html',locals(),context_instance=RequestContext(request))

def detail(request,video_id):
	try:
		video=Video.objects.get(pk=video_id)
		back=request.META['HTTP_REFERER']
	except Video.DoesNotExist:
		raise Http404
	return render_to_response('videos/detail.html',locals(), context_instance=RequestContext(request))

views.py
from django.http import HttpResponseRedirect

def home(request):
	return HttpResponseRedirect("videos/")

templates/videos/detail.html
<h1>{{video.module_title_part}}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<p>

<iframe width="560" height="349" src="http://www.youtube.com/embed/{{video.video_youtube_id}}" frameborder="0" allowfullscreen></iframe>

</p>

<a href="{{ back }}">Go Back</a>

templates/videos/index.html
<h1>Select a Stream</h1>
{% if streams_list %}
	<ul>
	{% for stream in streams_list %}
		<li><a href="streams/{{stream.pk}}">{{stream.stream_title}}</a></li>
		<ul>
			<li>{{stream.description}}</li>
			<li>Total Modules: {{stream.module_count}}</li>
			<li>Total Length: </li>
		</ul>		
	{%endfor%}
	</ul>
{% else %}
	<p>No streams are available</p>
{% endif %}

templates/videos/stream_detail.html
<h1>Modules in {{stream.stream_title}}</h1>
{% if associations_list %}
	<ol>
	{% for association in associations_list %}
		{% with module=association.association_module_id  %}
			<p>
			<li>{{ module }}</li>
			Description: {{module.module_description}}
			<ol>
				{% for video in module.video_set.all %}
					<li><a href="../../{{video.pk}}">Part {{video.video_part}}</a> [{{video.video_type}}, Length= ]</li>
				{%endfor%}
			</ol>
			</p>
		{% endwith %}
	{% endfor %}
	</ol>
{% else %}
	There are no modules in this stream
{% endif %}

<a href="../../">Go Back</a>